### ISSUE TITLE
Eigenvalues did not converge

### ISSUE THREAD

**Issue by vwarrier** [devlaming/mgreml#1]
Hello,

Thanks for this very nice method. I'm trying to run mgreml but ran into an eigenvalue convergence issue at step 2, Cleaning your data. 

The log is below. 

Any suggestions?

Best,
Varun

Code:
`Your call: 
./mgreml.py \
--grm /rds/project/rds-Nl99R8pHODQ/UKB/Imaging_genetics/unrelated_grm \
--pheno /rds/project/rds-Nl99R8pHODQ/UKB/Imaging_genetics/SA_v2.txt \
--covar /rds/project/rds-Nl99R8pHODQ/UKB/Imaging_genetics/mgreml_covar.txt \
--out /rds/project/rds-Nl99R8pHODQ/UKB/Imaging_genetics/mgreml_output/SA_withoutglobal 
`

##error
2022-02-07 21:29:59,394: 2. CLEANING YOUR DATA
2022-02-07 21:29:59,394: Current memory usage is 7484MB
2022-02-07 21:29:59,395: CHECKING FOR DUPLICATES
2022-02-07 21:29:59,398: CHECKING FOR MULTICOLLINEARITY IN YOUR FIXED-EFFECT COVARIATES
2022-02-07 21:29:59,405: JOINING YOUR DATA
2022-02-07 21:29:59,405: There are 37510 individuals in your phenotype data
2022-02-07 21:29:59,405: There are 30765 individuals in your GRM
2022-02-07 21:29:59,405: There are 31797 individuals in your covariate data
2022-02-07 21:29:59,527: Keeping only the 30749 overlapping individuals
2022-02-07 21:30:06,047: DROPPING PROBLEMATIC INDIVIDUALS BECAUSE OF MISSING PHENOTYPES AND/OR COVARIATES
2022-02-07 21:30:06,047: Current memory usage is 7443MB
2022-02-07 21:30:18,708: Found 0 individuals with missing data on one or more covariates
2022-02-07 21:30:18,708: Setting all phenotypes to missing for those individuals
2022-02-07 21:30:18,728: Dropping 0 out of 30749 individuals from data for whom all phenotypes are now missing
2022-02-07 21:30:23,724: FINALISING DATA BEFORE MGREML ANALYSIS
2022-02-07 21:30:23,724: Current memory usage is 7479MB
2022-02-07 21:30:23,724: Computing eigenvalue decomposition of the GRM
2022-02-07 21:30:23,724: WARNING! This may take a long time and double current memory usage...
2022-02-07 22:50:29,299: Eigenvalue decomposition completed
2022-02-07 22:50:29,356: Current memory usage is 14724MB
2022-02-07 22:50:29,356: Dropping GRM from memory
2022-02-07 22:50:29,370: Current memory usage is 7511MB
2022-02-07 22:50:29,370: Applying the canonical transformation to your data
2022-02-07 22:50:29,370: Sample size prior to the canonical transformation is 30749
2022-02-07 22:50:29,370: Adjusting for 20 leading eigenvectors to control for population stratification
2022-02-07 22:50:34,502: Traceback (most recent call last):
  File "/rds/user/rb643/hpc-work/Tools/mgreml/./mgreml.py", line 25, in main
    myMgremlData = reader.MgremlReader(parser, logger, process)
  File "/rds/user/rb643/hpc-work/Tools/mgreml/mgreml/data/reader.py", line 229, in __init__
    self.FinaliseData()
  File "/rds/user/rb643/hpc-work/Tools/mgreml/mgreml/data/reader.py", line 1427, in FinaliseData
    vEVRY = np.linalg.eigvalsh(mCorrY)
  File "<__array_function__ internals>", line 180, in eigvalsh
  File "/home/rb643/.conda/envs/mgreml/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 1163, in eigvalsh
    w = gufunc(a, signature=signature, extobj=extobj)
  File "/home/rb643/.conda/envs/mgreml/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 94, in _raise_linalgerror_eigenvalues_nonconvergence
    raise LinAlgError("Eigenvalues did not converge")
numpy.linalg.LinAlgError: Eigenvalues did not converge

**Comment by eawslob** [comment]
Hi Varun,
It seems like the method is having trouble with computing the eigendecomposition of the phenotypic correlation matrix. 
Could you see inspect how correlated your (phenotypic) variables are? Is this matrix positive semidefinite?
Best, Eric

**Comment by devlaming** [comment]
Hi Varun and Eric,

Although MGREML can crash in cash of severe multicollinearity, this should not be the point at which it crashes. Even when the matrix of phenotypes is rank deficient, its correlation matrix has an eigenvalue decomposition that numpy can readily calculate.

This error message is the result of input data (phenotypes and/or covariates) being encoded incorrectly. Either those data contain non-numerical values or missing values have been coded incorrectly.

MGREML can handle the missing values in the phenotype (and/or covariate data) when encoded using the following formats (comma-separated list of formats, with the right format between single quotation marks):

‘’, ‘#N/A’, ‘#N/A N/A’, ‘#NA’, ‘-1.#IND’, ‘-1.#QNAN’, ‘-NaN’, ‘-nan’, ‘1.#IND’, ‘1.#QNAN’, ‘<NA>’, ‘N/A’, ‘NA’, ‘NULL’, ‘NaN’, ‘n/a’, ‘nan’, ‘null’.

I obtained this list from https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html, which is the reference manual of the pandas function that MGREML uses to read in phenotype and covariate data.

Finally, please note that your phenotypes and covariates should not contain non-numeric stuff other than missing values, of course.

Hope this resolves that particular issue.

P.S. in case of strong phenotypic multicollinearity, consider using the --pairwise option.

Kind regards,
Ronald
